config/routes.rb
Krb::Application.routes.draw do
    
  get "git/status"

  resources :user_sessions
    match "login" => "user_sessions#new", :as => :login
    match "logout" => "user_sessions#destroy", :as => :logout
  
  resources :users, :only => [:new, :create, :edit, :update]
    match "signup" => "users#new", :as => :signup
    match "registration_complete" => "users#registration_complete", :as => :registration_complete
    
  match '/auth/:provider/callback', :to => 'sessions#create'
  
  match "invalid_activation_code" => "activations#invalid_activation_code", :as => :invalid_activation_code
  match "activated" => "activations#activated", :as => :activated
  match "activate/:activation_code" => "activations#create", :as => :activation
  match "send_activation/:user_id" => "users#send_activation"
  match "profiles/upload_photo" => "profiles#upload_photo"
  match "profiles/process_upload_photo" => "profiles#process_upload_photo"
  match "profiles/crop_photo" => "profiles#crop_photo"
  match "profiles/hide_profile_notice" => "profiles#hide_profile_notice"
  
  resources :profiles
  
  resources :thoughts, :only => [:create]
  
  resources :blogs, :only => [:show, :index]
    match "/blogs/author/:name" => "blogs#author"
    match "/blogs/tag/:tag" => "blogs#tag"
  
  resources :user_threads do
    member do
      post :report_comment
      post :remove_comment
    end
  end
  
  resources :resumes do
    
    member do
      get :delete
      get :select_theme
    end
    
    resources :resume_educations do
      member do
        get :delete
        get :toggle
      end
      
      collection do
        post :order
        get :delete_all
      end
      
    end
    
    resources :resume_work_experiences do
      member do
        get :delete
      end
      
      collection do
        post :order
      end
    end
    
    resources :resume_references do
      member do
        get :delete
        post :order
      end
      
      collection do
        post :order
      end
    end
    
    resources :resume_hidden_fields do
      collection do
        post :update_section
      end
    end
    
    resources :resume_section_orders do
      collection do
        put :update_order
      end
    end
    
    resources :resume_themes, :only => [:update]
    
    resources :resume_settings, :only => [:update]
    
    resources :resume_keywords, :only => [:create, :destroy]
    
  end
  
  resources :password_resets
  
  root :to => 'home#index'

  match "/users" => "home#index"
  match "/dashboard" => "dashboard#index"
  
  match "/:url" => "resumes#show"  
    
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  before_filter :require_user, :only => :index
  
  def index 
    @resumes = current_user.resumes
    
    @popular_resumes = Resume.get_popular_resumes(current_user)
    
    @resume_viewers = Resume.get_resume_viewers(@resumes, current_user)
    
    @missing = Profile.missing_fields(current_user.profile)
  end
  
  
  
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.haml
- @title_for_layout = "Dashboard"
- @body_id = "dashboard"

- if @missing.count > 0 && @profile.hide_profile_notification == false
  #profile_complete_notice.result_success
    %p 
      Your profile is yet completed. In order to complete it, you need to fill in #{@missing.join(", ")}
      %span#hide_profile_complete_notice Hide this notice |

%h2#thoughtbox_header Share your thought

#thoughtbox_wrapper.blue_region
  = render :partial => "shared/user_image"
  #thoughtbox
    #thoughtbox_left
      #thoughtbox_right
        = text_field_tag "thoughtbox_message", "Type your thought here"
    = image_tag "resume/gobutton.png", :id => "share_thought", :alt => "Share thought"
  
  .clearfloat
  
  #thoughts_chars_count_wrapper
    %span#thoughts_chars_count 115
    characters left
  
.clearfloat

/ Left col starts
.left_col

  / Your resumes starts
  %h2 Your resumes
  #your_resumes.blue_region
    %ul#resumes_list.item_list
      - if @resumes.count > 0
        - @resumes.each do |resume|
          %li.white_region
            .left
              = link_to resume.title, edit_resume_path(resume)
              %p.timestamp
                Last updated #{resume.updated_at.strftime("%b %d, %Y %H:%M %p")}
            .options
              %a.delete{:title => "Delete", :href => "/resumes/#{resume.id}/delete"}
              %a.view_live{:title => "View", :href => "#{resume.url}", :target => "_blank"}
              = link_to "", edit_resume_path(resume), :class => :edit
    = link_to(image_tag("resume/createAResume.png", :alt => "Create resume"), new_resume_path)
  / Your resumes ends
  
  / Most viewed resumes start
  %h2 Your most viewed resumes
  #resume_statistics.blue_region
    - if @popular_resumes.count > 0
      %ul#popular_resumes.item_list
        - @popular_resumes.each do |resume|
          %li.white_region
            .left
              = link_to resume.title, edit_resume_path(resume)
            .options
              %a.analytic
              %span
                %strong
                  = resume.views
    - else
      %p.white_region Statistics will appear here as your resumes being viewed
  / Most viewed resumes end
  
  / Who's viewed your resumes starts
  %h2 Who's viewed your resumes
  #resume_viewers.blue_region
    - if @resume_viewers.count > 0
      - @resume_viewers.each do |user|
        = link_to((image_tag user.gravatar_url, :class => :user_image), profile_path(user.username))
      .clearfloat
    - else
      %p.white_region{:style => "float:none"} Statistics will appear here as people start viewing your resumes
  / Who's viewed your resumes ends
    
/ Right col starts
.right_col

  / Your profile starts
  %h2 Your profile
  #your_profile.blue_region
    = render :partial => "shared/user_image"
    
    %ul#your_profile_header.white_region
      %li#your_profile_name
        = @profile.first_name 
        = @profile.last_name
      %li
        - if !@profile.job_title.blank?
          = @profile.job_title
        - else
          %a.edit_profile_btn Edit your profile
    .clearfloat
  / Your profile ends

.clearfloat