config/routes.rb
Krb::Application.routes.draw do
    
  get "git/status"

  resources :user_sessions
    match "login" => "user_sessions#new", :as => :login
    match "logout" => "user_sessions#destroy", :as => :logout
  
  resources :users, :only => [:new, :create, :edit, :update]
    match "signup" => "users#new", :as => :signup
    match "registration_complete" => "users#registration_complete", :as => :registration_complete
    
  match '/auth/:provider/callback', :to => 'sessions#create'
  
  match "invalid_activation_code" => "activations#invalid_activation_code", :as => :invalid_activation_code
  match "activated" => "activations#activated", :as => :activated
  match "activate/:activation_code" => "activations#create", :as => :activation
  match "send_activation/:user_id" => "users#send_activation"
  match "profiles/upload_photo" => "profiles#upload_photo"
  match "profiles/process_upload_photo" => "profiles#process_upload_photo"
  match "profiles/crop_photo" => "profiles#crop_photo"
  match "profiles/hide_profile_notice" => "profiles#hide_profile_notice"
  
  resources :profiles
  
  resources :thoughts, :only => [:create]
  
  resources :blogs, :only => [:show, :index]
    match "/blogs/author/:name" => "blogs#author"
    match "/blogs/tag/:tag" => "blogs#tag"
  
  resources :user_threads do
    member do
      post :report_comment
      post :remove_comment
    end
  end
  
  resources :resumes do
    
    member do
      get :delete
      get :select_theme
    end
    
    resources :resume_educations do
      member do
        get :delete
        get :toggle
      end
      
      collection do
        post :order
        get :delete_all
      end
      
    end
    
    resources :resume_work_experiences do
      member do
        get :delete
      end
      
      collection do
        post :order
      end
    end
    
    resources :resume_references do
      member do
        get :delete
        post :order
      end
      
      collection do
        post :order
      end
    end
    
    resources :resume_hidden_fields do
      collection do
        post :update_section
      end
    end
    
    resources :resume_section_orders do
      collection do
        put :update_order
      end
    end
    
    resources :resume_themes, :only => [:update]
    
    resources :resume_settings, :only => [:update]
    
    resources :resume_keywords, :only => [:create, :destroy]
    
  end
  
  resources :password_resets
  
  root :to => 'home#index'

  match "/users" => "home#index"
  match "/dashboard" => "dashboard#index"
  
  match "/:url" => "resumes#show"  
    
end

app/views/shared/_back_to_resume.html.erb
<%= link_to "Back to resume", edit_resume_path(@resume), :class => "go_back" %>

app/views/shared/_flash_notice.html.erb
<% if flash[:notice] %>
  <div class="result_success"><%= flash[:notice] %></div>
<% end %>

app/views/shared/_footer.html.haml
#footer
  #footer_inner
    #footer_nav_wrapper
      .footer_left
        %p#copyright_statement 2011 &copy; Rails Resume Builder
      .footer_right
        %ul#footer_nav
          %li 
            %a#back_to_top{:style => 'border:0'} Back to top
          %li 
            %a{:href => 'http://krbdr.tumblr.com'} Blog
          %li
            = link_to 'Home', root_url
      .clearfloat
    

app/views/shared/_form_errors.html.erb
<div class="result_error"><%= f.error_messages :header_message => "", :message => "" %></div>

app/views/shared/_formatting_examples.html.erb
<div id="formatting_tips" class="overlay_modal" style="display:none">
  
  <h2>Formatting Tips</h2>
   
  <%= image_tag "resume/closeLoginForm.png", :class => "close_overlay" %>
   
  <div class="blue_region">
   
    <div class="white_region">
      <p>To use bullets, start a new line with a * followed by a space</p>
      <p class="example">Example:</p>
      <p>* Designed and developed a CD labels generator</p>
      <p class="example">will be generated as</p>
      <ul style="list-style:disc; padding-left:13px">
        <li>Designed and developed a CD labels generator</li>
      </ul>
    </div>
     
    <div class="white_region">
      <p>To bold text, surround it with * and *</p>
      <p class="example">Example:</p>
      <p>*Javascript developer* </p>
      <p class="example">will be generated as</p>
      <p><b>Javascript developer</b></p>
    </div>
   
    <div class="white_region">
     <p>To use italics, surround text with _ and _</p>
     <p class="example">Example:</p>
     <p>_March 29th, 2011_</p>
     <p class="example">will be generated as</p>
     <p><i>March 29th, 2011</i></p>
    </div>
   
    <div class="white_region">
     <p>To underline text, surround it with + and +</p>
     <p class="example">Example:</p>
     <p>+Ruby on Rails developer+</p>
     <p class="example">will be generated as</p>
     <p><u>Ruby on Rails developer</u></p>
    </div>
    
    <div class="white_region">
      <p>To add line break, hit the Enter (Return on Mac) key twice</p>
      <p class="example">Example:</p>
      <p>
        Javascript<br /><br />
        HTML<br /><br />
        CSS
      </p>
      <p class="example">will be generated as</p>
      <p>
        Javascript<br />
        HTML<br />
        CSS
      </p>
    </div>
    
  </div>
  
 </div>

app/views/shared/_formatting_tips.html.haml
.clearfloat
.formatting_tips_wrapper
  %span.formatting_tips.trigger_overlay{:rel => 'formatting_tips'} formatting tips

app/views/shared/_header.html.haml
#header_wrapper
  
  #header
  
    %h1#app_logo 
      %a{:href => '/'} Killer Resume Builder
    
    - if logged_in?
    
      %ul#top_panel
        %li
          = link_to "Logout", logout_path, :class => :last
        %li
          %a.edit_profile_btn Edit Profile
        %li
          = link_to 'Dashboard', :controller => :dashboard, :action => :index
        %li
          = link_to "#{user_profile.first_name} #{user_profile.last_name}", profile_path(current_user.username)
        %li#header_profile_photo
          = image_tag current_user.gravatar_url, :class => :user_image
    - else
      = link_to image_tag("resume/login.png", :alt => "Login"), login_path, :id => "login_link"
      = link_to(image_tag("resume/signup.png"), signup_path, :id => "signup_link")
    
    .clearfloat
    
  #header_nav_wrapper

app/views/shared/_profile_overlay.html.haml
#profile_overlay_wrapper.account_overlay_wrapper{:style => 'display:none'}
  .account_overlay_left
    = render :partial => "shared/user_image"
    = image_tag "resume/changePhotoBtn.png", :id => "change_photo_btn", :alt => "Change photo"
  .account_overlay_right
    .inner
      #profile_image_cropper{:style => 'display:none; height:400px'}
        #change_avatar
          %p{:style => 'margin-top:10px'} We are using #{current_user.email}
          %p{:style => 'margin:10px 0'} Your avatar change on gravatar.com might take a while to be updated by our system
          %a#back_to_edit_profile Back to profile details
      #profile_details_input
        = form_for @profile, :html => { :id => :profile_form } do |profile_form|
          %h2
            = image_tag "resume/profileDetailsHeader.png", :alt => "Profile"
          
          #edit_profile_message{:style => 'display:none'}
            
          .form_row
            %label First Name
            = profile_form.text_field :first_name, :class => :textbox, :id => "profile_first_name"
        
          .form_row
            %label Last Name
            = profile_form.text_field :last_name, :class => :textbox, :id => "profile_last_name"
        
          .form_row
            %label City
            = profile_form.text_field :city, :class => :textbox, :id => "profile_city"
          
          .form_row
            %label State/Province
            = profile_form.text_field :state, :class => :textbox, :id => "profile_state"
          
          .form_row
            %label Country
            = profile_form.select :country, Carmen::country_names, :selected => @profile.country
          
          .form_row
            %label Postal Code
            = profile_form.text_field :postal_code, :class => :textbox, :id => "profile_postal_code"
          
          .form_row
            %label Job Function
            = profile_form.select "job_category_id", get_job_categories, :selected => @profile.job_category_id
        
          .form_row
            %label Industry
            = profile_form.select "job_industry_id", get_job_industries, :selected => @profile.job_industry_id
        
          .form_row
            %label Job Title
            = profile_form.text_field :job_title, :class => :textbox, :id => "profile_job_title"
            
          %input#profile_id{:type => 'hidden', :value => @profile.id}
          
          = image_tag "resume/updateProfileBtn.png", :alt => "Update", "class" => 'account_overlay_update_btn', :id => "update_profile_btn"
          .clearfloat
  = image_tag "resume/closeOverlay.png", :id => "close_profile_overlay", :class => "close_overlay"
  
.clearfloat

app/views/shared/_resume_section_renderer.html.erb
<% for s in @section_order %>
	<%= render :partial => "shared/resume/show/#{@theme.slug}/#{s}" unless @hidden_fields.include?(s)  %>
<% end %>

app/views/shared/_resume_user_image.html.erb
<%= image_tag @resume.user.gravatar_url, :class => :user_image unless !@resume.resume_setting.display_personal_photo %>

app/views/shared/_section_name_editor.html.erb
<% 
section_id = 0

@resume.resume_section_orders.each do |rso|
  if rso.section == section
    section_id = rso.id
  end
end

%>

<div class="section_name_editor_wrapper">
	<h2 class="section_name_editable" title="Click to rename section"><%= @section_names[section] %></h2>
	<input class="section_name_editor" type="text" value="<%= @section_names[section] %>" title="Click to rename this section" style="display:none" />
	<span class="update_section_name blue_btn" style="display:none" rel="<%= section %>">Update</span>
	<span class="cancel_update_section_name green_btn" style="display:none">Cancel</span>
	
	<input type="hidden" class="resume_section_order_id" value="<%= section_id %>" />
</div>

app/views/shared/_top_panel.html.erb
<div style="display:none" id="updated_status">Your resume has been updated</div>

app/views/shared/_user_image.html.erb
<%# photo == "male.png" || photo == "female.png" ? image_tag("resume/#{photo}", :class => "user_image") : image_tag("upload/#{photo}", :class => :user_image) %>

<%= image_tag current_user.gravatar_url, :class => "user_image" %>