config/routes.rb
Krb::Application.routes.draw do
    
  get "git/status"

  resources :user_sessions
    match "login" => "user_sessions#new", :as => :login
    match "logout" => "user_sessions#destroy", :as => :logout
  
  resources :users, :only => [:new, :create, :edit, :update]
    match "signup" => "users#new", :as => :signup
    match "registration_complete" => "users#registration_complete", :as => :registration_complete
    
  match '/auth/:provider/callback', :to => 'sessions#create'
  
  match "invalid_activation_code" => "activations#invalid_activation_code", :as => :invalid_activation_code
  match "activated" => "activations#activated", :as => :activated
  match "activate/:activation_code" => "activations#create", :as => :activation
  match "send_activation/:user_id" => "users#send_activation"
  match "profiles/upload_photo" => "profiles#upload_photo"
  match "profiles/process_upload_photo" => "profiles#process_upload_photo"
  match "profiles/crop_photo" => "profiles#crop_photo"
  match "profiles/hide_profile_notice" => "profiles#hide_profile_notice"
  
  resources :profiles
  
  resources :thoughts, :only => [:create]
  
  resources :blogs, :only => [:show, :index]
    match "/blogs/author/:name" => "blogs#author"
    match "/blogs/tag/:tag" => "blogs#tag"
  
  resources :user_threads do
    member do
      post :report_comment
      post :remove_comment
    end
  end
  
  resources :resumes do
    
    member do
      get :delete
      get :select_theme
    end
    
    resources :resume_educations do
      member do
        get :delete
        get :toggle
      end
      
      collection do
        post :order
        get :delete_all
      end
      
    end
    
    resources :resume_work_experiences do
      member do
        get :delete
      end
      
      collection do
        post :order
      end
    end
    
    resources :resume_references do
      member do
        get :delete
        post :order
      end
      
      collection do
        post :order
      end
    end
    
    resources :resume_hidden_fields do
      collection do
        post :update_section
      end
    end
    
    resources :resume_section_orders do
      collection do
        put :update_order
      end
    end
    
    resources :resume_themes, :only => [:update]
    
    resources :resume_settings, :only => [:update]
    
    resources :resume_keywords, :only => [:create, :destroy]
    
  end
  
  resources :password_resets
  
  root :to => 'home#index'

  match "/users" => "home#index"
  match "/dashboard" => "dashboard#index"
  
  match "/:url" => "resumes#show"  
    
end

app/models/resume_education.rb
class ResumeEducation < ActiveRecord::Base
  
  belongs_to :resume
  
  validates_presence_of :institution, :begin_date, :degree
  
end

app/controllers/resume_educations_controller.rb
class ResumeEducationsController < ApplicationController
  
  include ResumeHelper
  
  before_filter :require_user, :verify_ownership
  
  def new
    @resume_education = ResumeEducation.new
    
    section_order = ResumeSectionOrder.where(:resume_id => params[:resume_id], :section => 'education').first
    
    @section_name = section_order.name
  end
  
  def create
    @resume_education = ResumeEducation.new(params[:resume_education])
    @resume_education.resume_id = params[:resume_id]
    if @resume_education.save
      redirect_to edit_resume_path(@resume)
    else
      render :action => :new
    end
  end
  
  def edit
    @resume_education = find_resume_education
    
    section_order = ResumeSectionOrder.where(:resume_id => params[:resume_id], :section => 'education').first
    
    @section_name = section_order.name
  end
  
  def update
    @resume_education = find_resume_education
    if @resume_education.update_attributes(params[:resume_education])
      flash[:notice] = "Education has been updated"
      redirect_to edit_resume_resume_education_path(@resume)
    else
      render :action => :edit
    end
  end
  
  def delete
    ResumeEducation.delete params[:id]
    redirect_to edit_resume_path(@resume)
  end
  
  def order
    orders = params[:order]
    
    weight = orders.count
    
    i = 0
    
    for id in orders
      edu = ResumeEducation.where(:resume_id => params[:resume_id], :id => id).first
      edu.update_attributes(:weight => weight)
      weight -= 1
    end
    
    render :json => {:success => 1}
  end
  
  private
  
  def find_resume_education
    ResumeEducation.where(:id => params[:id], :resume_id => params[:resume_id]).first
  end
  
end

app/helpers/resume_educations_helper.rb
module ResumeEducationsHelper
end

app/views/resume_educations/edit.html.erb
<% 
@title_for_layout = "Edit #{@section_name}"
@body_id = "resume_education"
%>

<%= render :partial => "shared/back_to_resume" %>

<%= form_for @resume_education, :url => resume_resume_education_path(@resume) do |f| %>

<div class="blue_region">
  
  <div class="box_top"></div>

  <div class="box">
    
    <h2><%= @title_for_layout %></h2>
    
    <% if flash[:notice] %>
      <div class="result_success"><%= flash[:notice] %></div>
    <% end %>
    
    <% if @resume_education.errors.count > 0 %>
      <%= render :partial => "shared/form_errors", :locals => {:f => f} %>
    <% end %>

    <div class="form_row">
    	<label>Institution</label>
    	<%= f.text_field :institution, :class => :textbox %>
    </div>

    <div class="form_row">
    	<label for="ResumeEducationBeginDate">Begin Date</label>
    	<%= f.text_field :begin_date, :class => :textbox %>
    </div>

    <div class="form_row">
    	<label for="ResumeEducationEndDate">End Date</label>
    	<%= f.text_field :end_date, :class => :textbox  %>
    </div>

    <div class="form_row">
    	<label for="ResumeEducationDegree">Degree</label>
    	<%= f.text_field :degree, :class => :textbox %>
    </div>

    <div class="form_row">
    	<label for="ResumeEducationFieldOfStudy">Field of Study</label>
    	<%= f.text_field :field_of_study, :class => :textbox %>
    </div>

    <div class="form_row">
    	<label for="ResumeEducationGpa">GPA</label>
    	<%= f.text_field :gpa, :class => :textbox %>
    </div>

    <div class="form_row">
    	<label for="ResumeEducationLocation">Location</label>
    	<%= f.text_field :location, :class => :textbox %>
    </div>

    <input src="/images/resume/updateSectionBtn.png" alt="Update" type="image" />
    
  </div>
  
</div>


<% end %>

app/views/resume_educations/new.html.erb
<% 
@title_for_layout = "Add #{@section_name}"
@body_id = "resume_education"
%>

<%= render :partial => "shared/back_to_resume" %>

<%= form_for @resume_education, :url => resume_resume_educations_path(@resume) do |f| %>

<div class="blue_region">
  
  <div class="box_top"></div>
  
  <div class="box">
    
    <h2><%= @title_for_layout %></h2>
    
    <% if @resume_education.errors.count > 0 %>
      <%= render :partial => "shared/form_errors", :locals => {:f => f} %>
    <% end %>

    <div class="form_row">
    	<label>Institution</label>
    	<%= f.text_field :institution, :class => :textbox %>
    </div>

    <div class="form_row">
    	<label for="ResumeEducationBeginDate">Begin Date</label>
    	<%= f.text_field :begin_date, :class => :textbox %>
    </div>

    <div class="form_row">
    	<label for="ResumeEducationEndDate">End Date</label>
    	<%= f.text_field :end_date, :class => :textbox  %>
    </div>

    <div class="form_row">
    	<label for="ResumeEducationDegree">Degree</label>
    	<%= f.text_field :degree, :class => :textbox %>
    </div>

    <div class="form_row">
    	<label for="ResumeEducationFieldOfStudy">Field of Study</label>
    	<%= f.text_field :field_of_study, :class => :textbox %>
    </div>

    <div class="form_row">
    	<label for="ResumeEducationGpa">GPA</label>
    	<%= f.text_field :gpa, :class => :textbox %>
    </div>

    <div class="form_row">
    	<label for="ResumeEducationLocation">Location</label>
    	<%= f.text_field :location, :class => :textbox %>
    </div>

    <input src="/images/resume/addItNowBtn.png" alt="Add It Now" type="image" />
    
  </div>
  
  <div class="box_bottom"></div>
  </div>

<% end %>