config/routes.rb
Krb::Application.routes.draw do
    
  get "git/status"

  resources :user_sessions
    match "login" => "user_sessions#new", :as => :login
    match "logout" => "user_sessions#destroy", :as => :logout
  
  resources :users, :only => [:new, :create, :edit, :update]
    match "signup" => "users#new", :as => :signup
    match "registration_complete" => "users#registration_complete", :as => :registration_complete
    
  match '/auth/:provider/callback', :to => 'sessions#create'
  
  match "invalid_activation_code" => "activations#invalid_activation_code", :as => :invalid_activation_code
  match "activated" => "activations#activated", :as => :activated
  match "activate/:activation_code" => "activations#create", :as => :activation
  match "send_activation/:user_id" => "users#send_activation"
  match "profiles/upload_photo" => "profiles#upload_photo"
  match "profiles/process_upload_photo" => "profiles#process_upload_photo"
  match "profiles/crop_photo" => "profiles#crop_photo"
  match "profiles/hide_profile_notice" => "profiles#hide_profile_notice"
  
  resources :profiles
  
  resources :thoughts, :only => [:create]
  
  resources :blogs, :only => [:show, :index]
    match "/blogs/author/:name" => "blogs#author"
    match "/blogs/tag/:tag" => "blogs#tag"
  
  resources :user_threads do
    member do
      post :report_comment
      post :remove_comment
    end
  end
  
  resources :resumes do
    
    member do
      get :delete
      get :select_theme
    end
    
    resources :resume_educations do
      member do
        get :delete
        get :toggle
      end
      
      collection do
        post :order
        get :delete_all
      end
      
    end
    
    resources :resume_work_experiences do
      member do
        get :delete
      end
      
      collection do
        post :order
      end
    end
    
    resources :resume_references do
      member do
        get :delete
        post :order
      end
      
      collection do
        post :order
      end
    end
    
    resources :resume_hidden_fields do
      collection do
        post :update_section
      end
    end
    
    resources :resume_section_orders do
      collection do
        put :update_order
      end
    end
    
    resources :resume_themes, :only => [:update]
    
    resources :resume_settings, :only => [:update]
    
    resources :resume_keywords, :only => [:create, :destroy]
    
  end
  
  resources :password_resets
  
  root :to => 'home#index'

  match "/users" => "home#index"
  match "/dashboard" => "dashboard#index"
  
  match "/:url" => "resumes#show"  
    
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  
  has_one :resume_personal_information, :dependent => :delete
  has_one :resume_field_work, :dependent => :delete
  has_one :resume_skill, :dependent => :delete
  has_one :resume_theme, :dependent => :delete
  has_one :resume_setting, :dependent => :delete
  
  has_many :resume_educations, :dependent => :delete_all, :order => "weight DESC"
  has_many :resume_keywords, :dependent => :delete_all
  has_many :resume_work_experiences, :dependent => :delete_all, :order => "weight DESC"
  has_many :resume_references, :dependent => :delete_all, :order => "weight DESC"
  has_many :resume_section_orders, :dependent => :delete_all, :order => "weight DESC"
  has_many :resume_hidden_fields, :dependent => :delete_all
  has_many :resume_viewers, :dependent => :delete_all, :order => "created_at DESC"
  has_many :visitor_infos, :dependent => :delete_all
  
  belongs_to :user
  
  validates_length_of :url, :minimum => 4
  validates_uniqueness_of :url
  validates_presence_of :title
  
  accepts_nested_attributes_for :resume_personal_information, :resume_skill, :resume_field_work, :resume_educations
  
  before_save :prep_url
  
  def self.get_popular_resumes(user)
    self.where("user_id = ?", user.id).order("views DESC").limit(5)
  end
  
  def self.get_resume_viewers(resumes, user)
    resume_ids = []
    
    resumes.each do |resume|
      resume_ids << resume.id
    end
    
    resume_viewers = ResumeViewer.where(:resume_id => resume_ids).find(:all)
    
    resume_viewer_ids = []
    
    resume_viewers.each do |resume_viewer|
      resume_viewer_ids << resume_viewer.id unless resume_viewer.user_id == user.id
    end
    
    viewers = User.includes(:profile).where(:id => resume_viewer_ids).limit(5).find(:all)
    viewers
  end
  
  private
  
  def prep_url
    self.url = to_slug(self.url).downcase
  end
  
  def to_slug(string)
    #strip the string
    ret = string.strip

    #blow away apostrophes
    ret.gsub! /['`]/,""

    # @ --> at, and & --> and
    ret.gsub! /\s*@\s*/, " at "
    ret.gsub! /\s*&\s*/, " and "

    #replace all non alphanumeric, underscore or periods with underscore
     ret.gsub! /\s*[^A-Za-z0-9\.\-]\s*/, '-'  

     #convert double underscores to single
     ret.gsub! /_+/,"-"

     #strip off leading/trailing underscore
     ret.gsub! /\A[_\.]+|[_\.]+\z/,""

     ret
  end
  
  
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  
  include ResumeHelper
  
  before_filter :require_user, :except => [:show]
  before_filter :verify_ownership, :except => [:show, :new, :create]
  
  def new
    @resume = Resume.new
  end
  
  def create
    
    @resume = Resume.new(:title => params[:resume][:title], :url => params[:resume][:url], :user_id => current_user.id)
            
    if @resume.save
      
      @resume.resume_personal_information = ResumePersonalInformation.create
      
      @resume.resume_skill = ResumeSkill.create
      
      @resume.resume_field_work = ResumeFieldWork.create
      
      @resume.resume_theme = ResumeTheme.create(:theme_id => Theme.default_theme.id)
      
      @resume.resume_setting = ResumeSetting.create
      
      ResumeSectionOrder.create_resume_section_order(@resume)
      
      redirect_to dashboard_path and return
    else
      render :action => :new
    end
  end
  
  def show
    @resume = Resume.find_by_url(params[:url])
    
    if !@resume.nil?
      @theme = Theme.find(@resume.resume_theme.theme_id)
      
      @section_names = ResumeSectionOrder.get_section_names(@resume)
      
      @section_order = ResumeSectionOrder.get_section_order(@resume)
      
      @keywords = ResumeKeyword.get_keywords(@resume)
      
    	@field_works = @resume.resume_field_work.field_works
    	
    	@hidden_fields = ResumeHiddenField.get_hidden_fields(@resume)
  	  
  	  update_analytics(@resume)
      
      render :layout => "themes/#{@theme.slug}"
    else
      redirect_to root_url and return
    end
  end
  
  def edit
    @section_names = ResumeSectionOrder.get_section_names(@resume)
    
    @settings = @resume.resume_setting
    
    @field_works = @resume.resume_field_work.field_works
  	
  	@hidden_fields = ResumeHiddenField.get_hidden_fields(@resume)
  end
  
  def update
    if @resume.update_attributes(params[:resume])
      flash[:notice] = "Your resume has been updated"
      redirect_to edit_resume_path(@resume)
    else
      render :action => :edit
    end
  end
  
  def delete
    @resume.destroy
    redirect_to dashboard_path and return
  end
  
  def select_theme
    @themes = Theme.get_all_themes
    render :layout => "theme_selector"
  end
  
  private
  
  def update_analytics(resume)
    user_agent = UserAgent.parse(request.user_agent)
	  
	  resume.visitor_infos.create(:browser => user_agent[2].product, :version => user_agent.version, :platform => user_agent[0].comment.join(" "), :ip_address => request.remote_addr, :domain_name => request.host)
	  
	  user_id = logged_in? ? current_user.id : 0
	  
	  resume.update_attributes(:views => resume.views + 1) unless (user_id != 0 && user_id == resume.user.id)
	  
	  resume.resume_viewers.create(:user_id => user_id)
  end
  
  def verify_ownership
    
    begin
      @resume = Resume.find(params[:id])
      
      if !@resume.user_id == current_user.id
        redirect_to dashboard_path
        return false
      end
      
      return true
    rescue
      redirect_to dashboard_path
      return false
    end
      
  end
 
end

app/helpers/resume_helper.rb
module ResumeHelper
  
  def find_resume_by_id
    begin
      @resume = Resume.find(params[:resume_id])
    rescue
      nil
    end
  end
  
  def manipulatable?
    if @resume
      @resume.user_id == current_user.id 
    else
      false
    end
  end
  
  def verify_ownership
    find_resume_by_id
    
    if !manipulatable?
      redirect_to dashboard_path
      return false
    end
    
    true
  end
  
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/shared/resume/edit/_education.html.erb
<div class="box_top"></div>
<div class="box">
	
	<%= render :partial => "shared/section_name_editor", :locals => {:section => "education"} %>
	
	<div class="section_options">
		<div class="options_label">Options</div>
		<div class="add">
		  <%= link_to "Add a new entry", new_resume_resume_education_path(@resume) %>
		</div>
		
		<% section_mode = @hidden_fields.include?("education") ? "disabled" : "active" %>
		
		<a class="enable_section" rel="education">Enable this section</a>
		<a class="disable_section" rel="education">Disable this section</a>
		
		<input type="hidden" class="section_mode" value="<%= section_mode %>" />
	</div>
	
	<div id="sort_education" class="sortable">
		<% @resume.resume_educations.each do |edu| %>
		  <div id="edu_<%= edu.id %>" class="ui-state-default">
		    <h3 class="institution_name"><%= edu.institution %></h3>
		    <p class="degree">
		      <%= edu.degree %>
		      <br />
		      (<%= edu.begin_date %> - <%= edu.end_date %>)
		    </p>
		    <a href="/resumes/<%=@resume.id%>/resume_educations/<%=edu.id%>/edit" class="edit_link"></a>
		    <a href="/resumes/<%=@resume.id%>/resume_educations/<%=edu.id%>/delete" class="delete_link"></a>
		  </div>
		<% end %>
	</div>
	
	<div class="clearfloat"></div>

</div>
<div class="box_bottom"></div>

app/views/shared/resume/edit/_field_works.html.erb
<div class="box_top"></div>
<div class="box">
	
	<div class="section_options">
		<div class="options_label">Options</div>
		
		<% section_mode = @hidden_fields.include?("field_works") ? "disabled" : "active" %>
		
	  <a class="enable_section" rel="field_works">Enable this section</a>
		<a class="disable_section" rel="field_works">Disable this section</a>

		<input type="hidden" class="section_mode" value="<%= section_mode %>" />
	</div>
	
	<%= render :partial => "shared/section_name_editor", :locals => {:section => "field_works"} %>
	
	<p>Links to your works (e.g. http://www.website.com)</p>
	
	<div class="clearfloat"></div>

	<%= f.fields_for :resume_field_work do |fw| %>
		<%= fw.text_area :field_works, :class => :markitup %>
	<% end %>
	
	<%= render :partial => 'shared/formatting_tips' %>

</div>
<div class="box_bottom"></div>

app/views/shared/resume/edit/_keywords.html.erb
<div class="box_top"></div>
<div class="box">
	<h2>Keywords</h2>
	<p>Enter your keywords. These keywords will be used as meta keywords for your resume.</p>
	<div id="keywordsMessage">
	    <% keywords_left = 20 - @resume.resume_keywords.count %>
		<span id="keywordsLeft"><%= keywords_left == 20 ? "You have 20 keywords left. Choose wisely." : "#{keywords_left} keywords left" %></span>
	</div>
	<div id="keywordsListWrapper">
		<div id="keywordsList">
			<% for keyword in @resume.resume_keywords %>
			    <div class="keyword_wrapper">
                	<div class="keyword"><%= keyword.keywords %></div>
                	<div rel="<%= keyword.id %>" class="keyword_remove">x</div>
                </div>
			<% end %>
		</div>
		<input type="text" id="keywordsInput" />
		<div class="clearfloat"></div>
	</div>
</div>
<div class="box_bottom"></div>

app/views/shared/resume/edit/_personal_information.html.erb
<div id="personal_information">
<%= f.fields_for :resume_personal_information do |pi| %>
<div class="box_top"></div>
<div class="box">

<%= render :partial => "shared/section_name_editor", :locals => {:section => "personal_information"} %>

<div class="clearfloat"></div>

<div class="form_row">
  <%= pi.label :full_name %>
	<%= pi.text_field :full_name, :class => :textbox %>
</div>

<div class="form_row">
  <%= pi.label :address %>
	<%= pi.text_field :address, :class => :textbox %>
</div>

<div class="form_row">
  <%= pi.label :city %>
	<%= pi.text_field :city, :class => :textbox %>
</div>

<div class="form_row">
  <label for="resume_resume_personal_information_attributes_state">State/Province</label>
	<%= pi.text_field :state, :class => :textbox %>
</div>

<div class="form_row">
	<%= pi.label :phone_number %>
	<%= pi.text_field :phone_number, :class => :textbox %>
</div>

<div class="form_row">
	<%= pi.label :fax_number %>
	<%= pi.text_field :fax_number, :class => :textbox %>
</div>

<div class="form_row">
	<%= pi.label :email %>
	<%= pi.text_field :email, :class => :textbox %>
</div>

<div class="form_row">
	<%= pi.label :website %>
	<%= pi.text_field :website, :class => :textbox %>
</div>

<div class="form_row">
	<label for="resume_resume_personal_information_attributes_bio">Bio / Summary</label>
	<div id="markItUpResumePersonalInformationBio" class="markItUp">
		<%= pi.text_area :bio, :class=> "markitup" %>
	</div>
	<%= render :partial => 'shared/formatting_tips' %>
</div>

<div class="form_row">
	<%= pi.label :facebook %>
	<%= pi.text_field :facebook, :class => :textbox %>
</div>

<div class="form_row">
	<%= pi.label :twitter %>
	<%= pi.text_field :twitter, :class => :textbox %>
</div>

<div class="form_row">
	<%= pi.label :flickr %>
	<%= pi.text_field :flickr, :class => :textbox %>
</div>

<div class="form_row">
	<%= pi.label :linkedin %>
	<%= pi.text_field :linkedin, :class => :textbox %>
</div>

<div class="form_row">
  <%= pi.label :github %>
  <%= pi.text_field :github, :class => :textbox %>
</div>

<div class="clearfloat"></div>
</div>
<div class="box_bottom"></div>
<% end %>
</div>

app/views/shared/resume/edit/_references.html.erb
<div class="box_top"></div>
<div class="box">
	
	<%= render :partial => "shared/section_name_editor", :locals => {:section => "references"} %>
	
	<div class="section_options">
		<div class="options_label">Options</div>
		<div class="add">
		  <%= link_to "Add a new entry", new_resume_resume_reference_path(@resume) %>
		</div>
		
		<% section_mode = @hidden_fields.include?("references") ? "disabled" : "active" %>
		
		<a class="enable_section" rel="references">Enable this section</a>
		<a class="disable_section" rel="references">Disable this section</a>

		<input type="hidden" class="section_mode" value="<%= section_mode %>" />
	</div>
	
	<div class="clearfloat"></div>
	
	<div id="sort_references" class="sortable">
	  <% @resume.resume_references.each do |ref| %>
	    <div id="ref_<%= ref.id %>" class="ui-state-default">
	      <a class="edit_link" href="/resumes/<%= @resume.id %>/resume_references/<%= ref.id %>/edit"></a>
	      <a class="delete_link" href="/resumes/<%= @resume.id %>/resume_references/<%= ref.id %>/delete"></a>
	      <ul class="reference_details">
	        <li><%= ref.name %>, <%= ref.title %></li>
	        <li><%= ref.organization %></li>
            <li><a href="mailto:<%= ref.email %>"><%= ref.email %></a></li>
	      </ul>
	    </div>
	  <% end %>
	</div>
	
	<div class="clearfloat"></div>
	
</div>
<div class="box_bottom"></div>

app/views/shared/resume/edit/_skills.html.erb
<div class="box_top"></div>
<div class="box">
	
<div class="section_options">
	<div class="options_label">Options</div>
	
	<% section_mode = "active" %>
	
	<% if @hidden_fields.include?("skills") %>
	    <a class="enable_section" rel="skills">Enable this section</a>
	    <% section_mode = "disabled" %>
	<% else %>
	    <a class="disable_section" rel="skills">Disable this section</a>
	<% end %>
	
	<input type="hidden" class="section_mode" value="<%= section_mode %>" />
</div>

<%= render :partial => "shared/section_name_editor", :locals => {:section => "skills"} %>

<div class="clearfloat"></div>
<div class="form_row">
	
	<%= f.fields_for :resume_skill do |s| %>
		<%= s.text_area :skills, :class => :markitup %>
	<% end %>
	
	<%= render :partial => 'shared/formatting_tips' %>
	
</div>
</div>
<div class="box_bottom"></div>

app/views/shared/resume/edit/_title.html.erb
<div id="title_url">
	<div class="box_top"></div>
	<div id="resume_basic_info_section" class="box">
		<%= f.label :title %>
		<div class="form_row">
			<%= f.text_field :title, :class => :textbox %>
		</div>
	</div>
	<div class="box_bottom"></div>
</div>

app/views/shared/resume/edit/_work_experience.html.erb
<div class="box_top"></div>
<div class="box">
	
	<%= render :partial => "shared/section_name_editor", :locals => {:section => "work_experience"} %>
	
	<div class="section_options">
		<div class="options_label">Options</div>
		
		<div class="add">
  	    <%= link_to "Add a new entry", new_resume_resume_work_experience_path(@resume) %>
  	</div>
  	    
  	<% section_mode = @hidden_fields.include?("work_experience") ? "disabled" : "active" %>
		
		<a class="enable_section" rel="work_experience">Enable this section</a>
		<a class="disable_section" rel="work_experience">Disable this section</a>
		
		<input type="hidden" class="section_mode" value="<%= section_mode %>" />
	</div>
	
	<div id="sort_work_experience" class="sortable">
		<% @resume.resume_work_experiences.each do |exp| %>
		  <div id="exp_<%= exp.id %>" class="ui-state-default">
		    <h3 class="organization_name"><%= exp.organization_name %></h3>
		    <div class="position_title"><%= exp.title %></div>
		    <div class="position_date"><%= exp.begin_date %> - <%= exp.end_date %></div>
		    <div class="clearfloat"></div>
		    <a href="/resumes/<%= @resume.id %>/resume_work_experiences/<%= exp.id %>/edit" class="edit_link"></a>
		    <a href="/resumes/<%= @resume.id %>/resume_work_experiences/<%= exp.id %>/delete" class="delete_link"></a>
		  </div>
		<% end %>
	</div>
	
	<div class="clearfloat"></div>

</div>
<div class="box_bottom"></div>